name: main
on:
  - pull_request
  - push
jobs:
  main:
    name: ${{matrix.node}}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dcodeIO/setup-node-nvm@master
        with:
          node-version: ${{matrix.node}}
      - run: yarn
      - run: yarn test
      - uses: codecov/codecov-action@v3
    strategy:
      matrix:
        node:
          - 18.3.0
